### ISSUE TITLE
接口请求代理如何处理？

### ISSUE THREAD

**Issue by yangzai316** [lankongmoxing/vue-cli-3.0.3-build-env#2]
你好，我本地开发，配置代理没有问题，项目很正常；部署上线，接口请求不了，单独测试接口，接口的发布是没有问题，感觉线上代理出问题了，没法请求接口了，报404....
很不解啊...

**Comment by yangzai316** [comment]
问题解决了，开发的代理配置，打包上线之后就没有了；线上的代理要在服务端做配置...

**Comment by lankongmoxing** [comment]
哎呀...
